services:
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel-app:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./laravel-app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
